### PR TITLE
Fix partially broken MX check

### PR DESCRIPTION
**Pull request by technoyes**
The MX check returns true even if the DNS lookup returns NXDomain (i.e the domain does not exist). Same goes for the case where the domain exists (Authority is present) but no MX records are found (Answer field is missing).

This PR fixes these issues and makes the check much more useful.

Note: Re-run of parcel is not included.

### CODE REVIEW

**Comment by technoyes** [comment]
Any idea if this if/when this could get merged?

And if a 1.1.2 release would be released any time soon?

**Comment by technoyes** [comment]
In the mean time anyone in need of this can use

```
yarn add technoyes/cross-email-validator#bugfix/mx-record-check-installable
```

which installs this PR plus the required parcel rebuild.

**Comment by RobertFischer** [comment]
Just saw this in my notifications -- sorry, they got somewhat buried.  Merging it now.

**Comment by technoyes** [comment]
No problem! Thanks for merging. Since the project is pretty mature, maybe run parcel, do a release and push to npm too?

**Comment by RobertFischer** [comment]
Will do.

**Comment by technoyes** [comment]
Thanks!

**Pull request merged**
